- hosts: all
  become: true
  tasks:
  - name: pulling flaskapp image from gar
    docker_image:
      name: us-east1-docker.pkg.dev/siva-477505/repo1/pythonimg2626:v1
      source: pull
  - name: running flaskapp container
    docker_container:
      name: flaskapp
      image: us-east1-docker.pkg.dev/siva-477505/repo1/pythonimg2626:v1
      state: started
      ports:
        - "85:5000"
